version: '3.1'

services: 
    zoobackend:
        image: zoobackend:v0.01
        #ports: 
            #- "3000:3000"
        volumes:
            - /home/zoo/zoo/docker/zooapp/app:/app
        deploy:
            labels: 
                - traefik.http.services.zoobackend.loadbalancer.server.port=3000
        networks: 
            - traefiknet
networks: 
    traefiknet:
        external: true